services:
  weaviate:
    image: semitechnologies/weaviate:latest
    container_name: weaviate
    ports:
      - "8080:8080"
    environment:
      QUERY_DEFAULTS_LIMIT: 20
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "./data"
      ENABLE_MODULES: "text2vec-openai"
    volumes:
      - ./data:/data
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cognify_app
    ports:
      - "5000:5000"
    volumes:
      - ./CognifyVault:/app
    depends_on:
      - weaviate
    restart: always
